[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install && CI=false npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  publish = "frontend/build"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/api-proxy/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
